services:
  - type: web
    name: rifas-backend
    env: node
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: postgresql://usuario:password@host:5432/rifasdb
      - key: JWT_SECRET
        value: supersecreto
      - key: PORT
        value: 3000
