services:
  - type: web
    name: rifas-backend
    env: node
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: postgresql://usuario:password@host:5432/rifasdb
      - key: JWT_SECRET
        value: supersecreto
      - key: PORT
        value: 3000
      # Configuración de Email (Resend SMTP)
      - key: SMTP_HOST
        value: smtp.resend.com
      - key: SMTP_PORT
        value: 465
      - key: SMTP_SECURE
        value: true
      - key: SMTP_USER
        value: resend
      - key: SMTP_PASS
        sync: false # Debes poner tu API Key de Resend aquí en el dashboard de Render
      - key: MAIL_FROM
        value: onboarding@resend.dev # O tu dominio verificado si ya tienes uno
